### ISSUE TITLE
Add avatar image to user object in Graphdb

### ISSUE THREAD

**Issue by tuxpiper** [ushahidi/project-pheme-data-interface#16]

**Comment by lauratolosi** [comment]
This is what we have for now: 

`PREFIX pheme: <http://www.pheme.eu/ontology/pheme#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
select * {
    ?a foaf:accountName ?name .
    ?a foaf:depiction ?avatar.
}`

**Comment by tuxpiper** [comment]
Thank you @lauratolosi , I'll plug it in.  We can substitute "_normal.jpeg" in the URL for "_bigger.jpeg" to get a bigger size :)
